backend:
  name: github
  repo: NetoReyes/puntoycoma
  branch: master

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "articulos"
    label: "Artículos"
    folder: "src/content/articulos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "descripcion", widget: "text" }
      - { label: "Categoría", name: "categoria", widget: "select", options: ["politica", "sociedad", "economia", "cultura", "opinion"] }
      - { label: "Fecha", name: "fecha", widget: "datetime" }
      - { label: "Imagen portada", name: "cover", widget: "image" }
      - { label: "Contenido", name: "body", widget: "markdown" }